name: Pull Request Tests

on:
  pull_request:
    branches:
      - main
      - development
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    # Only run tests for specific branch prefixes (hotfix, improve, feature, bugfix)
    if: |
      contains(github.event.pull_request.title, 'hotfix') ||
      contains(github.event.pull_request.title, 'improve') ||
      contains(github.event.pull_request.title, 'feature') ||
      contains(github.event.pull_request.title, 'bugfix') ||
      contains(github.event.pull_request.head.ref, 'hotfix') ||
      contains(github.event.pull_request.head.ref, 'improve') ||
      contains(github.event.pull_request.head.ref, 'feature') ||
      contains(github.event.pull_request.head.ref, 'bugfix')

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db?schema=public

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
